server:
  port: ${PORT:8082}



spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vieirajluis/springcloud/blob/master/config-repo
          basedir: target/config